[tools]
bun = "latest"
go = "latest"
java = "21"
jq = "latest"
kubectl = "latest"
node = "latest"
opam = "2.3.0"
opentofu = "latest"
python = "3.12.2"
rust = "latest"
terragrunt = "latest"
zig = "latest"
ant = "latest"
gh = "latest"
elixir = "latest"
yarn = "4.6.0"

