[tools]
bun = "latest"
go = "latest"
java = "21"
jq = "latest"
kubectl = "latest"
node = "23.1.0"
opam = "2.1.4"
opentofu = "latest"
python = "3.12"
rust = "latest"
terragrunt = "latest"
zig = "latest"
ant = "latest"
