[tools]
bun = "latest"
elixir = "latest"
go = "latest"
java = "21"
jq = "latest"
kubectl = "latest"
opam = "2.1.4"
opentofu = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
terragrunt = "latest"
zig = "latest"
