# https://alacritty.org/config-alacritty.html
[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 20.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[bell]
duration = 0

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.5

[window.dimensions]
columns = 100
lines = 85

[general]
live_config_reload = true
